trigger:
- main

pool:
  name: 'Default'

variables:
  imageName: iwebashu/recruit  # Customize this
  tag: latest

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'docker-hub-connection'  # Must match the one you created
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
